[build]
  base    = "/"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION       = "20"
  NPM_FLAGS          = "--legacy-peer-deps"
  MAINTENANCE_MODE   = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

